---
- hosts: all
  become: yes

  tasks:

  - name: add parameters net.ifnames=0 biosdevname=0 to grub 
    lineinfile:
      path: /etc/default/grub
      regexp: '^GRUB_CMDLINE_LINUX='
      line: GRUB_CMDLINE_LINUX="net.ifnames=0 biosdevname=0"
      validate: grub2-mkconfig %s


 
      

 
